<a href="https://colab.research.google.com/github/kxrrym03/Flower-Morphometrics-Analysis/blob/main/Flower_Morphometrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [4]:
from google.colab import files
uploaded = files.upload()

Saving extended_flower_morphometrics.csv to extended_flower_morphometrics.csv

In [5]:
df = pd.read_csv('extended_flower_morphometrics.csv')
df.shape

(200000, 9)

In [6]:
df.head()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,stem_thickness_mm,petal_density_pct,chlorophyll_index,native_altitude_m,species
0,4.317614,3.028292,6.092543,3.166156,5.063025,63.558150,55.913100,886.568622,Rose
1,5.531122,3.887679,5.497682,2.374855,4.656235,52.368783,26.383116,247.206553,Iris Versicolor
2,5.908407,2.576321,6.264473,1.785481,5.893707,36.056153,61.562376,1197.921681,Orchid
3,6.855284,2.764075,4.606390,1.175031,4.854951,55.623467,38.671083,940.401196,Iris Versicolor
4,5.412124,3.691987,1.800383,0.221225,2.528513,60.218904,34.674831,679.473136,Iris Setosa

In [7]:
df.tail()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,stem_thickness_mm,petal_density_pct,chlorophyll_index,native_altitude_m,species
199995,4.310318,3.203669,4.608296,3.181966,6.685197,74.660851,57.874758,669.014693,Rose
199996,5.441338,2.540579,3.065710,3.081896,6.412263,36.600376,49.377932,410.593633,Rose
199997,7.634411,2.717171,5.527709,0.544835,7.115064,64.974656,55.590180,1141.716023,Orchid
199998,5.840849,1.975244,8.855018,2.062708,6.483508,54.200146,28.485977,921.509666,Orchid
199999,6.177141,3.201139,4.291363,2.253710,4.440774,72.793139,34.516120,1143.161113,Orchid

In [8]:
df.isnull().sum()

sepal_length_cm      0
sepal_width_cm       0
petal_length_cm      0
petal_width_cm       0
stem_thickness_mm    0
petal_density_pct    0
chlorophyll_index    0
native_altitude_m    0
species              0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.describe()

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,stem_thickness_mm,petal_density_pct,chlorophyll_index,native_altitude_m
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,6.494801,3.701722,5.660341,2.339627,6.756894,53.202820,45.769422,568.676301
std,2.389844,1.219015,3.769632,1.761005,4.301134,13.891707,10.579623,277.763702
min,1.314396,-0.681257,-0.040491,-1.097662,-1.357669,-0.531327,2.766288,-562.840890
25%,4.976431,2.955377,3.371251,1.137561,3.772243,43.519517,38.443302,374.074507
50%,5.732968,3.406310,4.901882,2.118828,5.459812,52.465437,45.348677,552.110497
75%,6.973427,4.003575,6.466747,3.107515,7.910897,62.153948,52.640398,749.846888
max,18.797057,11.130567,24.222782,10.444469,28.019564,116.494596,98.869354,1954.432880

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   sepal_length_cm    200000 non-null  float64
 1   sepal_width_cm     200000 non-null  float64
 2   petal_length_cm    200000 non-null  float64
 3   petal_width_cm     200000 non-null  float64
 4   stem_thickness_mm  200000 non-null  float64
 5   petal_density_pct  200000 non-null  float64
 6   chlorophyll_index  200000 non-null  float64
 7   native_altitude_m  200000 non-null  float64
 8   species            200000 non-null  object
dtypes: float64(8), object(1)
memory usage: 13.7+ MB

In [13]:
df.dtypes

sepal_length_cm      float64
sepal_width_cm       float64
petal_length_cm      float64
petal_width_cm       float64
stem_thickness_mm    float64
petal_density_pct    float64
chlorophyll_index    float64
native_altitude_m    float64
species               object
dtype: object

In [14]:
df.columns

Index(['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm',
       'petal_width_cm', 'stem_thickness_mm', 'petal_density_pct',
       'chlorophyll_index', 'native_altitude_m', 'species'],
      dtype='object')